target/release/raytracer.exe --frame_iterations 50 --max_triangles 5 > result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 10 >> result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 15 >> result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 20 >> result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 25 >> result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 30 >> result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 35 >> result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 40 >> result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 50 >> result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 60 >> result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 70 >> result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 80 >> result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 90 >> result.txt
target/release/raytracer.exe --frame_iterations 50 --max_triangles 100 >> result.txt
